export const viewerElements = [
  {
    key: "entrance",
    x: 574,
    y: 909,
    label: "입구",
    kind: "glass-door",
    angle: 0,
    anchor: 0.66,
    scale: 1,
    info: true,
  },
  {
    key: "exit",
    x: 270,
    y: 9,
    label: "출구",
    kind: "exit-door",
    angle: 0,
    anchor: 0.64,
    scale: 1,
    info: true,
  },
  {
    key: "window",
    x: 581,
    y: 727,
    label: "창문",
    kind: "window",
    angle: 0,
    anchor: 0.64,
    scale: 1,
    info: true,
  },
  {
    key: "fan",
    x: 231,
    y: 647,
    label: "순환",
    kind: "fan",
    angle: -0.45,
    anchor: 0.74,
    scale: 1,
    info: true,
  },
  {
    key: "thermometer",
    x: 101,
    y: 700,
    label: "온도계",
    kind: "thermometer",
    angle: -1.476,
    anchor: 0.74,
    scale: 1,
    info: true,
  },
  {
    key: "cooler",
    x: 364,
    y: 385,
    label: "공조",
    kind: "cooler",
    angle: 0,
    anchor: 0.72,
    scale: 1,
    info: true,
  },
  {
    key: "partition-note",
    x: 206,
    y: 574,
    label: "가벽",
    kind: "partition",
    angle: 0,
    anchor: 0.72,
    scale: 1,
    info: true,
  },
  {
    key: "mural",
    x: 332,
    y: 764,
    label: "니치",
    kind: "mural",
    angle: 1.571,
    anchor: 0.42,
    scale: 1,
    info: false,
  },
  {
    key: "wall-shelf-a",
    x: 332,
    y: 629,
    label: "선반",
    kind: "shelf",
    angle: 1.571,
    anchor: 0.52,
    scale: 1,
    info: false,
  },
  {
    key: "wall-shelf-b",
    x: 293,
    y: 921,
    label: "선반",
    kind: "shelf",
    angle: 0,
    anchor: 0.52,
    scale: 1,
    info: false,
  },
  {
    key: "center-counter",
    x: 199,
    y: 921,
    label: "진열",
    kind: "counter",
    angle: 0,
    anchor: 0.5,
    scale: 1,
    info: false,
  },
  {
    key: "low-table",
    x: 435,
    y: 657,
    label: "테이블",
    kind: "round-table",
    angle: 0,
    anchor: 0.5,
    scale: 1,
    info: false,
  },
  {
    key: "plant-entry",
    x: 233,
    y: 489,
    label: "식물",
    kind: "plant",
    angle: 0.25,
    anchor: 0.74,
    scale: 1,
    info: false,
  },
  {
    key: "plant-north",
    x: 394,
    y: 825,
    label: "식물",
    kind: "plant",
    angle: -0.2,
    anchor: 0.72,
    scale: 1,
    info: false,
  },
];
