export const viewerElements = [
  {
    key: "entrance",
    x: 576,
    y: 928,
    label: "입구",
    kind: "glass-door",
    angle: -1.571,
    anchor: 0.66,
    scale: 1.5,
    info: true,
  },
  {
    key: "window",
    x: 480,
    y: 362,
    label: "창문",
    kind: "window",
    angle: 3.142,
    anchor: 0.64,
    scale: 1,
    info: true,
  },
  {
    key: "fan",
    x: 421,
    y: 695,
    label: "순환",
    kind: "fan",
    angle: 1.571,
    anchor: 0.74,
    scale: 1,
    info: true,
  },
  {
    key: "thermometer",
    x: 81,
    y: 733,
    label: "온도계",
    kind: "thermometer",
    angle: 0,
    anchor: 0.74,
    scale: 1,
    info: true,
  },
  {
    key: "cooler",
    x: 158,
    y: 424,
    label: "공조",
    kind: "cooler",
    angle: -0.785,
    anchor: 0.72,
    scale: 1,
    info: true,
  },
  {
    key: "partition-note",
    x: 197,
    y: 538,
    label: "가벽",
    kind: "partition",
    angle: 1.309,
    anchor: 0.72,
    scale: 1,
    info: true,
  },
  {
    key: "mural",
    x: 360,
    y: 781,
    label: "니치",
    kind: "mural",
    angle: 3.142,
    anchor: 0.42,
    scale: 1,
    info: false,
  },
  {
    key: "wall-shelf-a",
    x: 349,
    y: 627,
    label: "선반",
    kind: "shelf",
    angle: 3.142,
    anchor: 0.52,
    scale: 1,
    info: false,
  },
  {
    key: "wall-shelf-b",
    x: 294,
    y: 932,
    label: "선반",
    kind: "shelf",
    angle: -1.571,
    anchor: 0.52,
    scale: 1,
    info: false,
  },
  {
    key: "center-counter",
    x: 191,
    y: 932,
    label: "진열",
    kind: "counter",
    angle: -1.571,
    anchor: 0.5,
    scale: 1,
    info: false,
  },
  {
    key: "low-table",
    x: 344,
    y: 112,
    label: "테이블",
    kind: "round-table",
    angle: 0,
    anchor: 0.5,
    scale: 1,
    info: false,
  },
  {
    key: "plant-entry",
    x: 656,
    y: 746,
    label: "식물",
    kind: "plant",
    angle: 2.344,
    anchor: 0.74,
    scale: 1,
    info: false,
  },
  {
    key: "plant-north",
    x: 456,
    y: 926,
    label: "식물",
    kind: "plant",
    angle: -2.294,
    anchor: 0.72,
    scale: 1,
    info: false,
  },
  {
    key: "window-6eizsou",
    x: 480,
    y: 628,
    label: "창문",
    kind: "window",
    angle: 3.142,
    anchor: 0.62,
    scale: 1,
    info: false,
  },
  {
    key: "window-b6k97zs",
    x: 210,
    y: 240,
    label: "창문",
    kind: "window",
    angle: 0,
    anchor: 0.62,
    scale: 1,
    info: false,
  },
  {
    key: "window-devs59t",
    x: 580,
    y: 725,
    label: "창문",
    kind: "window",
    angle: 1.571,
    anchor: 0.62,
    scale: 1,
    info: false,
  },
  {
    key: "round-table-4x1skae",
    x: 120,
    y: 656,
    label: "테이블",
    kind: "round-table",
    angle: 0.785,
    anchor: 0.62,
    scale: 1,
    info: false,
  },
  {
    key: "round-table-v3tzx4o",
    x: 148,
    y: 613,
    label: "테이블",
    kind: "round-table",
    angle: 0.785,
    anchor: 0.62,
    scale: 1,
    info: false,
  },
  {
    key: "window-c3o1r00",
    x: 122,
    y: 307,
    label: "창문",
    kind: "window",
    angle: 1.571,
    anchor: 0.62,
    scale: 1,
    info: false,
  },
  {
    key: "round-table-ytuvp7x",
    x: 187,
    y: 580,
    label: "테이블",
    kind: "round-table",
    angle: 0.785,
    anchor: 0.62,
    scale: 1,
    info: false,
  },
  {
    key: "round-table-w99mt06",
    x: 344,
    y: 163,
    label: "테이블",
    kind: "round-table",
    angle: 0,
    anchor: 0.62,
    scale: 1,
    info: false,
  },
  {
    key: "fan-ojdlwqf",
    x: 245,
    y: 695,
    label: "순환",
    kind: "fan",
    angle: -2.286,
    anchor: 0.62,
    scale: 1,
    info: true,
  },
  {
    key: "fan-sleo4u1",
    x: 415,
    y: 245,
    label: "순환",
    kind: "fan",
    angle: 1.571,
    anchor: 0.62,
    scale: 1,
    info: true,
  },
  {
    key: "window-zydgg6w",
    x: 50,
    y: 420,
    label: "창문",
    kind: "window",
    angle: 0,
    anchor: 0.62,
    scale: 1,
    info: false,
  },
  {
    key: "plant-wg2pgt8",
    x: 335,
    y: 436,
    label: "식물",
    kind: "plant",
    angle: 2.339,
    anchor: 0.62,
    scale: 1,
    info: false,
  },
];
