export const viewerElements = [
  {
    key: "entrance",
    x: 574,
    y: 927,
    label: "입구",
    kind: "glass-door",
    angle: -1.571,
    anchor: 0.66,
    scale: 1.5,
    info: true,
  },
  {
    key: "exit",
    x: 272,
    y: 23,
    label: "출구",
    kind: "exit-door",
    angle: 1.571,
    anchor: 0.64,
    scale: 1,
    info: true,
  },
  {
    key: "window",
    x: 466,
    y: 362,
    label: "창문",
    kind: "window",
    angle: 3.142,
    anchor: 0.64,
    scale: 1,
    info: true,
  },
  {
    key: "fan",
    x: 245,
    y: 695,
    label: "순환",
    kind: "fan",
    angle: -2.283,
    anchor: 0.74,
    scale: 1,
    info: true,
  },
  {
    key: "thermometer",
    x: 97,
    y: 687,
    label: "온도계",
    kind: "thermometer",
    angle: 0.368,
    anchor: 0.74,
    scale: 1,
    info: true,
  },
  {
    key: "cooler",
    x: 134,
    y: 433,
    label: "공조",
    kind: "cooler",
    angle: -0.785,
    anchor: 0.72,
    scale: 1,
    info: true,
  },
  {
    key: "partition-note",
    x: 197,
    y: 538,
    label: "가벽",
    kind: "partition",
    angle: 1.309,
    anchor: 0.72,
    scale: 1,
    info: true,
  },
  {
    key: "mural",
    x: 348,
    y: 772,
    label: "니치",
    kind: "mural",
    angle: 3.142,
    anchor: 0.42,
    scale: 1,
    info: false,
  },
  {
    key: "wall-shelf-a",
    x: 349,
    y: 627,
    label: "선반",
    kind: "shelf",
    angle: 3.142,
    anchor: 0.52,
    scale: 1,
    info: false,
  },
  {
    key: "wall-shelf-b",
    x: 294,
    y: 932,
    label: "선반",
    kind: "shelf",
    angle: -1.571,
    anchor: 0.52,
    scale: 1,
    info: false,
  },
  {
    key: "center-counter",
    x: 191,
    y: 932,
    label: "진열",
    kind: "counter",
    angle: -1.571,
    anchor: 0.5,
    scale: 1,
    info: false,
  },
  {
    key: "low-table",
    x: 435,
    y: 657,
    label: "테이블",
    kind: "round-table",
    angle: 0,
    anchor: 0.5,
    scale: 1,
    info: false,
  },
  {
    key: "plant-entry",
    x: 345,
    y: 432,
    label: "식물",
    kind: "plant",
    angle: 2.344,
    anchor: 0.74,
    scale: 1,
    info: false,
  },
  {
    key: "plant-north",
    x: 459,
    y: 931,
    label: "식물",
    kind: "plant",
    angle: -2.294,
    anchor: 0.72,
    scale: 1,
    info: false,
  },
  {
    key: "window-6eizsou",
    x: 576,
    y: 738,
    label: "창문",
    kind: "window",
    angle: 1.571,
    anchor: 0.62,
    scale: 1,
    info: true,
  },
  {
    key: "window-b6k97zs",
    x: 122,
    y: 318,
    label: "창문",
    kind: "window",
    angle: 1.571,
    anchor: 0.62,
    scale: 1,
    info: true,
  },
];
